dist: trusty

language: d

d:
  - dmd
  - dmd-beta
  - ldc
  - ldc-beta

addons:
  postgresql: 9.6
  apt:
    packages:
      - libevent-dev # is need for scod

services: postgresql

env:
  global:
    - CONN_STRING="--conninfo=dbname=postgres"
    - TESTS_OPTS="--conninfo=dbname=postgres --native-host=localhost --native-port=5432"

before_script:
  - psql -c 'create database "dpq2-test"' -U postgres

script:
  - dub run dpq2:integration_tests --build=unittest -- $TESTS_OPTS
  - dub run dpq2:integration_tests --build=release -- $TESTS_OPTS

matrix:
  include:
    - d: dmd-2.078.3

      script:
        - dub run dpq2:integration_tests --build=unittest-cov -- $TESTS_OPTS
        - dub run dpq2:example --build=release -- $CONN_STRING
        - dub build --build=ddox

      before_install:
        - dub fetch dscanner
        - dub fetch doveralls

      after_success:
        - dub run doveralls
        - bash <(curl -s https://codecov.io/bash)

      cache: { directories: [$HOME/.dub] }

      deploy:
        provider: pages
        skip_cleanup: true
        keep-history: true
        github_token: $GITHUB_API_KEY
        on:
          branch: master
