dist: trusty

language: d

d:
  - dmd
  #- gdc
  - ldc

addons:
  postgresql: 9.6

services: postgresql

before_install:
  - dub fetch dscanner
  - dub fetch doveralls

before_script:
  - psql -c 'create database "dpq2-test"' -U postgres

script: ./.test.sh "dbname=postgres"

after_success:
  - rm -f .\.-*.lst
  - if [ ${DC} = "dmd" ]; then dub run doveralls; fi
  - if [ ${DC} = "dmd" ]; then bash <(curl -s https://codecov.io/bash); fi
