dist: trusty

language: d

addons:
  postgresql: 9.6

services: postgresql

matrix:
  include:
    -d: dmd

      before_install:
        - dub fetch dscanner
        - dub fetch doveralls

      after_success:
        - dub run doveralls
        - bash <(curl -s https://codecov.io/bash)

      deploy:
        provider: pages
        skip_cleanup: true
        keep-history: true
        github_token: $GITHUB_API_KEY
        on:
          branch: master

    -d: ldc

before_script:
  - psql -c 'create database "dpq2-test"' -U postgres

script: ./.test.sh "dbname=postgres"
